
package com.sortedset.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.tdev.discoveryagent.service.FunctionRequirement;
import com.tdev.discoveryagent.service.ObjectFactory;
import com.tdev.discoveryagent.service.QosRequirement;
import com.tdev.discoveryagent.service.RepuRequirement;
import com.tdev.discoveryagent.service.ServiceList;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JuddiAgentWebservice", targetNamespace = "http://service.discoveryagent.tdev.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JuddiAgentWebservice {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.tdev.discoveryagent.service.ServiceList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.discoveryagent.tdev.com/JuddiAgentWebservice/findServicesRequest", output = "http://service.discoveryagent.tdev.com/JuddiAgentWebservice/findServicesResponse")
    public ServiceList findServices(
        @WebParam(name = "arg0", partName = "arg0")
        FunctionRequirement arg0,
        @WebParam(name = "arg1", partName = "arg1")
        QosRequirement arg1,
        @WebParam(name = "arg2", partName = "arg2")
        RepuRequirement arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3);

}
